name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Copy .env
        run: cp .env.example .env
      - name: Create Application key
        run: php artisan key:generate
      - name: Run test suite
        run: php artisan test
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:githubdeploy
      - name: Deploy to Tailscale Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 100.99.28.19
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /srv/inventaris.binsarjr.com/
            git pull
            composer install --no-dev --optimize-autoloader --no-interaction --no-progress --no-suggest
