name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Copy .env
        run: cp .env.example .env
      - name: Create Application key
        run: php artisan key:generate
      - name: Run test suite
        run: php artisan test
